name: GH Sanity Check
run-name: ${{ github.actor }} is checking GL vs GH
on: [push]
jobs:
  test-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world triggered by a ${{ github.event_name }} event."