name: GH Sanity Check
run-name: ${{ github.actor }} is checking GL vs GH
on: [workflow_dispatch]
jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 18.20.0
      - run: echo "Releasing now"
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}