name: GH Sanity Check
run-name: ${{ github.actor }} is checking GL vs GH
on: [workflow_dispatch]
jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: 20
      - name: Install dependencies
        run: npm install semantic-release @semantic-release/git @semantic-release/github
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}